name: 'Palladio Build Deployment'
description: 'Build of Palladio Project'
inputs:
  build-repository:  
    description: 'Repository to deploy to'
    required: true
    default: ${{ github.repository }}
  source-path:
    description: 'Path to source that is to be deployed'
    required: true
    default: ''
    
runs:
  using: "composite"
  steps:
      - name: Create single repository name
        run: echo '::set-output name=REPO_NAME::${{ input.build-repository }} | cut -d/ -f 2 | tr [:upper:] [:lower:]' #removes "PalladioSimulator/" from repository name
        id: repo-name-generator
      - name: Deploy to nightly
        if: ${{ github.ref_name == 'master' || github.ref_name == 'main'}}
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ${{ inputs.deploy-updatesite }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '${{ secrets.REMOTE_TARGET/steps.repo-name-generator.outputs.REPO_NAME }}/nightly'
      - name: Deploy to branch
        if: ${{ github.ref_name != 'master' && github.ref_name != 'main'}}
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ${{ inputs.deploy-updatesite }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '${{ secrets.REMOTE_TARGET/steps.repo-name-generator.outputs.REPO_NAME/github.ref_name }}' 
       
